### PR TITLE
Scaffold React components so that initial demo runs

### LINKED ISSUE #63: Out of sync with the tutorial – client app broken
When following the tutorial, [this step](https://www.apollographql.com/docs/tutorial/client.html#react-apollo) breaks because `<Pages>` is missing most of the child components at this point.

I'll try to address it in a PR but it seems to be a bit of a rabbit hole.

### PR DESCRIPTION
**Pull request by borekb**
Resolves #63 
Related: https://github.com/apollographql/apollo/pull/317

### CODE REVIEW

**Comment by borekb** [comment]
Note: I'm still going through the tutorial, a7b3418 is the first attempt to fix it.

**Comment by borekb** [comment]
Different approach taken in 8f3dbb4: instead of modifying `pages/index.js` as in a7b3418, all empty components are scaffolded to something like:

```jsx
// pages/launches.js
import React from 'react';

export default function Launches() {
    return <div />;
}
```

This way, the app runs even in the early stage of the tutorial.

**Comment by TheRobBrennan** [comment]
This is what I needed. Thanks!!

**Comment by ro-savage** [comment]
Ran into the same issue and came here to do a PR.

Is the a reason this hasn't been merged? 

@borekb

**Comment by borekb** [comment]
I don't know – it has been part of https://github.com/apollographql/apollo/issues/329 which has been partially merged and partially reworked by the Apollo team. Maybe @daniman or @peggyrayzis would know?

**Pull request merged**
