### PR TITLE
Fix Client launch with error : no exported member 'loginVariables'

### PR DESCRIPTION
**Pull request by Stackingit**
Fixing compile issue #190

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Thanks for sending this @Stackingit! Quick ping, do you want to sign the CLA? I separately found this fix, and can send a separate PR with it if you don't want.

**Comment by Stackingit** [comment]
@JoshuaKGoldberg it was signed a while ago and ready for merge, but happy for you to create another :)

**Comment by Smankusors** [comment]
guys, there's #194, #202, #208... I'm wondering why this haven't merged yet?

**Comment by StephenBarlow** [comment]
Apologies for the delay! This is resolved in #237

**Pull request closed without merging**
