### PR TITLE
Remove duplicate launch

### PR DESCRIPTION
**Pull request by martinbonnin**

### CODE REVIEW

**Comment by jpvajda** [comment]
@martinbonnin 👋 I've been doing some work in this repo to update this project to React 18, is this still a valid change you want merged in?

**Comment by martinbonnin** [comment]
Yup, this removes a duplicate launch. It's pretty much a quickfix though. Ideally, we'd make the tutorial work again using the spaceX API or something else.

**Comment by jpvajda** [comment]
@martinbonnin ah yes. I'm doing a lot of updates to this tutorial to get in a better working state that's a good suggestion. Is there any concerns that this is failing tests?

**Comment by martinbonnin** [comment]
The CI [has been failing for a while unfortunately](https://github.com/apollographql/fullstack-tutorial/commits/subscriptions). I'm not sure how much of a problem that is given that the endpoint is still reachable. I don't think this is related to this change.

**Pull request merged**
